spring.application.name=microservice.config
my.greetings=hello world
my.app.name=Bismi App
my.app.description=Welcome to ${my.app.name
my.list.values=One,Two,Three
db.connection={connectionString:'http://__', userName:'test', password:'pass'}
db.port=8080
db.host=127.0.0.1
management.endpoints.web.exposure.include=*